name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore dotnetapp/
    - name: Build
      run: dotnet build dotnetapp/ --no-restore
    - name: Test
      run: dotnet test dotnetapp/ --no-build --verbosity normal
      # - name: Azure WebApp
      #uses: Azure/webapps-deploy@v2
      #with:
      #  app-name: "dotnetapp"
      # slot-name: "test"
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        # package: # optional, default is .
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        # images: 
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        # configuration-file: # optional
        # Enter the start up command. For ex. dotnet run or dotnet run
        # startup-command: # optional
